OnInit(function(requires)
    requires "Class"
    requires "Shop"
    requires "Utilities"

    local Setup = Class()

    function Setup.create(shop, aoe, tax)
        local this = CreateShop(shop, aoe, tax)

        local damage = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNSteelMelee", "Damage")
        local armor = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNHumanArmorUpOne", "Armor")
        local strength = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNGauntletsOfOgrePower", "Strength")
        local agility = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility", "Agility")
        local intelligence = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNMantleOfIntelligence", "Intelligence")
        local health = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNHealthStone", "Health")
        local mana = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNManaStone.blp", "Mana")
        local attackSpeed = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNGlove.blp", "Attack Speed")
        local movement = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNBootsOfSpeed", "Movement")
        local spellPower = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNPriestAdept.blp", "Spell Power")
        local cooldown = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNSpellBookBLS.blp", "Cooldown")
        local regeneration = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNScrollOfRegenerationGreen.blp", "Regeneration")
        local consumable = ShopAddCategory(shop, "ReplaceableTextures\\CommandButtons\\BTNPotionGreenSmall", "Consumable")

        ShopAddItem(shop, BootsOfSpeed.code, movement)
        ShopAddItem(shop, AnkhOfReincarnation.code, consumable)
        ShopAddItem(shop, PotionOfRestoration.code, consumable)
        ShopAddItem(shop, MaskOfDeath.code, regeneration)
        ShopAddItem(shop, CloakOfFlames.code, damage)
        ShopAddItem(shop, CommomShield.code, armor)
        ShopAddItem(shop, HeavyHammer.code, damage)
        ShopAddItem(shop, AssassinsDagger.code, damage)
        ShopAddItem(shop, IronAxe.code, damage)
        ShopAddItem(shop, SimpleBow.code, agility)
        ShopAddItem(shop, SummoningBook.code, spellPower + cooldown)
        ShopAddItem(shop, Courier.code, consumable)
        ShopAddItem(shop, LifeCrystal.code, health)
        ShopAddItem(shop, ManaCrystal.code, mana)
        ShopAddItem(shop, LifeEssenceCrystal.code, regeneration)
        ShopAddItem(shop, CrystalRing.code, regeneration + spellPower)
        ShopAddItem(shop, HomecomingStone.code, movement)
        ShopAddItem(shop, BraceletOfIntelligence.code, intelligence)
        ShopAddItem(shop, ClawsOfAgility.code, agility)
        ShopAddItem(shop, GauntletOfStrength.code, strength)
        ShopAddItem(shop, GlovesOfHaste.code, attackSpeed)
        ShopAddItem(shop, Platemail.code, armor)
        ShopAddItem(shop, RustySword.code, damage)
        ShopAddItem(shop, OrbOfFire.code, damage)
        ShopAddItem(shop, OrbOfFrost.code, damage)
        ShopAddItem(shop, OrbOfLight.code, damage)
        ShopAddItem(shop, OrbOfLightning.code, damage)
        ShopAddItem(shop, OrbOfSands.code, damage)
        ShopAddItem(shop, OrbOfSouls.code, damage + regeneration)
        ShopAddItem(shop, OrbOfThorns.code, damage)
        ShopAddItem(shop, OrbOfVenom.code, damage)
        ShopAddItem(shop, OrbOfWater.code, damage)
        ShopAddItem(shop, OrbOfWind.code, damage + movement)
        ShopAddItem(shop, OrbOfDarkness.code, damage)
        ShopAddItem(shop, SphereOfPower.code, spellPower)
        ShopAddItem(shop, BootsOfTheBraves.code, movement + health + attackSpeed + cooldown)
        ShopAddItem(shop, BootsOfAgility.code, movement + agility)
        ShopAddItem(shop, BootsOfIntelligence.code, movement + intelligence)
        ShopAddItem(shop, BootsOfStrength.code, movement + strength)
        ShopAddItem(shop, BootsOfRestoration.code, movement + regeneration + health)
        ShopAddItem(shop, BootsOfFlames.code, movement + damage)
        ShopAddItem(shop, GoldenBoots.code, movement + regeneration + damage)
        ShopAddItem(shop, HeavyBoots.code, movement + attackSpeed + damage)
        ShopAddItem(shop, SilverBoots.code, movement + armor + health)
        ShopAddItem(shop, BerserkerBoots.code, movement + attackSpeed + damage)
        ShopAddItem(shop, RunicBoots.code, movement + health + mana + spellPower)
        ShopAddItem(shop, GoldenSword.code, damage)
        ShopAddItem(shop, GoldenPlatemail.code, armor + health)
        ShopAddItem(shop, FusedLifeCrystals.code, health)
        ShopAddItem(shop, InfusedManaCrystal.code, mana)
        ShopAddItem(shop, ElementalShard.code, health + mana + regeneration)
        ShopAddItem(shop, HardenedShield.code, health + armor)
        ShopAddItem(shop, MaskOfMadness.code, regeneration)
        ShopAddItem(shop, GlovesOfSpeed.code, attackSpeed)
        ShopAddItem(shop, GlaiveScythe.code, agility + strength + intelligence)
        ShopAddItem(shop, MageStick.code, spellPower + mana + regeneration)
        ShopAddItem(shop, SorcererRing.code, mana + regeneration + spellPower)
        ShopAddItem(shop, WarriorBlade.code, damage + attackSpeed)
        ShopAddItem(shop, BlackNavaja.code, damage)
        ShopAddItem(shop, OrcishAxe.code, damage)
        ShopAddItem(shop, EnhancedHammer.code, damage)
        ShopAddItem(shop, EmeraldShoulderPlate.code, health + strength)
        ShopAddItem(shop, SteelArmor.code, health + armor)
        ShopAddItem(shop, WarriorHelmet.code, strength + regeneration)
        ShopAddItem(shop, SoulScyther.code, damage + strength + agility + intelligence)
        ShopAddItem(shop, GlovesOfSilver.code, attackSpeed)
        ShopAddItem(shop, WarriorShield.code, health + armor)
        ShopAddItem(shop, MageStaff.code, spellPower + intelligence + health + regeneration)
        ShopAddItem(shop, DemonicMask.code, damage + regeneration)
        ShopAddItem(shop, MagmaHelmet.code, strength + regeneration)
        ShopAddItem(shop, ChillingAxe.code, damage)
        ShopAddItem(shop, HolyBow.code, damage + agility)
        ShopAddItem(shop, LightningSpear.code, damage + attackSpeed)
        ShopAddItem(shop, DesertRing.code, mana + regeneration + spellPower)
        ShopAddItem(shop, SoulSword.code, damage + regeneration)
        ShopAddItem(shop, NatureStaff.code, spellPower + intelligence + health)
        ShopAddItem(shop, ToxicDagger.code, damage)
        ShopAddItem(shop, OceanicMace.code, damage)
        ShopAddItem(shop, WindSword.code, damage + movement)
        ShopAddItem(shop, SphereOfFire.code, spellPower)
        ShopAddItem(shop, SphereOfWater.code, spellPower)
        ShopAddItem(shop, SphereOfNature.code, spellPower)
        ShopAddItem(shop, SphereOfDivinity.code, spellPower)
        ShopAddItem(shop, SphereOfLightning.code, spellPower)
        ShopAddItem(shop, SphereOfDarkness.code, spellPower)
        ShopAddItem(shop, SphereOfAir.code, spellPower)
        ShopAddItem(shop, EternityStone.code, health + regeneration)
        ShopAddItem(shop, FusionCrystal.code, health + mana + regeneration)
        ShopAddItem(shop, WizardStone.code, health + mana + regeneration)
        ShopAddItem(shop, AncientStone.code, health + mana + regeneration + spellPower)
        ShopAddItem(shop, KnightBlade.code, damage + attackSpeed)
        ShopAddItem(shop, RitualDagger.code, damage + regeneration)
        ShopAddItem(shop, GiantsHammer.code, damage)
        ShopAddItem(shop, GreedyAxe.code, damage)
        ShopAddItem(shop, SaphireShoulderPlate.code, health + strength)
        ShopAddItem(shop, FlamingArmor.code, health + armor)
        ShopAddItem(shop, DragonHelmet.code, health + strength + regeneration)
        ShopAddItem(shop, ReapersEdge.code, spellPower + strength + agility + intelligence)
        ShopAddItem(shop, GlovesOfGold.code, attackSpeed)
        ShopAddItem(shop, CommanderShield.code, armor + health)
        ShopAddItem(shop, SorcererStaff.code, spellPower + health + intelligence + regeneration)
        ShopAddItem(shop, BookOfFlames.code, spellPower + damage + intelligence)
        ShopAddItem(shop, BookOfOceans.code, spellPower + intelligence + mana)
        ShopAddItem(shop, BookOfNature.code, spellPower + intelligence + regeneration)
        ShopAddItem(shop, BookOfLight.code, spellPower + intelligence + regeneration)
        ShopAddItem(shop, BookOfChaos.code, spellPower + intelligence + health)
        ShopAddItem(shop, BookOfIce.code, spellPower + intelligence + armor)
        ShopAddItem(shop, HellishMask.code, damage + regeneration)
        ShopAddItem(shop, EnflamedBow.code, damage + agility)
        ShopAddItem(shop, RingOfConversion.code, mana + regeneration)
        ShopAddItem(shop, AncientSphere.code, spellPower + mana + health + regeneration)
        ShopAddItem(shop, LegendaryBladeI.code, spellPower + damage + attackSpeed)
        ShopAddItem(shop, TriedgeSword.code, damage)
        ShopAddItem(shop, CrownOfRightouesness.code, mana + regeneration + spellPower)
        ShopAddItem(shop, HeatingCloak.code, mana + health + damage)
        ShopAddItem(shop, HammerOfNature.code, damage + strength + spellPower)
        ShopAddItem(shop, ElementalSpin.code, regeneration + spellPower + intelligence)
        ShopAddItem(shop, NecklaceOfVigor.code, health + mana + spellPower)
        ShopAddItem(shop, ThundergodSpear.code, attackSpeed + damage + spellPower)
        ShopAddItem(shop, WizardStaff.code, intelligence + regeneration + spellPower + health)
        ShopAddItem(shop, PhilosopherStone.code, regeneration + mana + health)
        ShopAddItem(shop, EntityScythe.code, spellPower + movement + agility + strength + intelligence)
        ShopAddItem(shop, LegendaryBladeII.code, spellPower + damage + attackSpeed)
        ShopAddItem(shop, Doombringer.code, damage)
        ShopAddItem(shop, DualDagger.code, damage + spellPower + regeneration)
        ShopAddItem(shop, ApocalypticMask.code, damage + regeneration)
        ShopAddItem(shop, RadiantHelmet.code, health + mana + strength + regeneration)
        ShopAddItem(shop, JadenShoulderPlate.code, health + strength)
        ShopAddItem(shop, MoonchantRing.code, health + mana + regeneration + intelligence)
        ShopAddItem(shop, BloodbourneShield.code, health + armor)
        ShopAddItem(shop, NatureGoddessStaff.code, spellPower + health + intelligence)
        ShopAddItem(shop, PhoenixAxe.code, spellPower + damage)
        ShopAddItem(shop, Weaver.code, mana + health + regeneration + spellPower + intelligence + cooldown)
        ShopAddItem(shop, LegendaryBladeIII.code, damage + spellPower + attackSpeed)
        ShopAddItem(shop, RedemptionSword.code, damage + spellPower)
        ShopAddItem(shop, ElementalStone.code, mana + health + regeneration)
        ShopAddItem(shop, SapphireHammer.code, damage + spellPower + strength)
        ShopAddItem(shop, FireBow.code, damage + spellPower + agility)
        ShopAddItem(shop, WarlockRing.code, health + spellPower + mana + regeneration + intelligence)
        ShopAddItem(shop, PhantomSpear.code, attackSpeed + spellPower + damage + movement)
        ShopAddItem(shop, MoonScyth.code, regeneration + spellPower + damage + movement + agility + strength + intelligence)
        ShopAddItem(shop, HolyScepter.code, spellPower + intelligence + regeneration)
        ShopAddItem(shop, MagusOrb.code, spellPower + intelligence + regeneration)
        ShopAddItem(shop, WeaverII.code, mana + health + regeneration + spellPower + intelligence + cooldown)
        ShopAddItem(shop, LegendaryBladeIV.code, spellPower + damage + attackSpeed)
        ShopAddItem(shop, SwordOfDomination.code, spellPower + damage)
        ShopAddItem(shop, ArcTrinity.code, damage + regeneration)
        ShopAddItem(shop, HolyHammer.code, spellPower + damage + strength + regeneration)
        ShopAddItem(shop, GluttonousAxe.code, damage + regeneration)
        ShopAddItem(shop, CrownOfGods.code, health + mana + regeneration + intelligence + spellPower)
        ShopAddItem(shop, BlackArmor.code, health + armor)
        ShopAddItem(shop, AngelicShield.code, health + armor)
        ShopAddItem(shop, HelmetOfEternity.code, health + mana + regeneration + strength)
        ShopAddItem(shop, ArcanaScepter.code, health + mana + regeneration + intelligence + spellPower)
        ShopAddItem(shop, ElementalSphere.code, health + mana + regeneration + spellPower + damage)
        ShopAddItem(shop, LegendaryBladeV.code, damage + spellPower + attackSpeed + movement)
        ShopAddItem(shop, CrownOfIce.code, spellPower + damage + strength + agility + intelligence)
        ShopAddItem(shop, GoldenHeart.code, health + armor)
        ShopAddItem(shop, LightningSword.code, damage + attackSpeed)
        ShopAddItem(shop, SakuraBlade.code, damage +  attackSpeed + movement)

        return this
    end

    function Setup.onInit()
        Setup.create(S2A('ngme'), 600, 0.5)

        for i = 0, bj_MAX_PLAYER_SLOTS do
            SetPlayerState(Player(i), PLAYER_STATE_RESOURCE_GOLD, GetPlayerState(Player(i), PLAYER_STATE_RESOURCE_GOLD) + 99999999)
        end
    end
end)